name: maple_dashboard
description: Dashboard for maple projects

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture & Management
  get: ^4.6.5

  #UI & UX
  sidebarx: ^0.6.0
  animations: ^2.0.2
  flutter_animator: ^3.2.2

  #Responsive & Adaptive
  #TODO: upgrade responsive_framework
  responsive_framework: ^0.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  #TODO: Update 'flutter_native_splash'
  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: ^0.9.3
  flutter_app_name: ^0.1.1

#configuration of splash screen, if something change, run: `flutter pub run flutter_native_splash:create`
flutter_native_splash:
  background_image: "assets/app_splash.png"

#configuration of flutter_icons, if something change, run: `flutter pub run flutter_launcher_icons:main`
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

#configuration of flutter_app_name, if something change, run: `flutter pub run flutter_app_name`
flutter_app_name:
  name: "Maple"

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png


  fonts:
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Variable.ttf
          weight: 400